/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videos_database_project2;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author VipinRajan
 */
public class View extends javax.swing.JFrame {
       public JFrame frame = new JFrame();
       protected JButton btnViewVideos = new JButton("View All Videos in Database");
       protected JButton btnAddVideos = new JButton("Add Video into Database");
       protected JButton btnSubmitVideos = new JButton("Submit");
       protected JTextField txtVideoTitle = new JTextField(10);
       protected JTextField txtURL = new JTextField(10);
       protected JTextField txtDesc = new JTextField(10);
       protected JLabel lblVideoTitle = new JLabel("Video Title: ");
       protected JLabel lblURL = new JLabel("URL: ");
       protected JLabel lblDesc = new JLabel("Description: ");
       public static JLabel lblError = new JLabel("Error! The video was not saved into the database!");
       public static JTable database = new JTable();
       public static DefaultTableModel datamodel1;      
       public JScrollPane jsp;
       int sx=frame.getSize().width;
       int sy=frame.getSize().height;
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        errUserLogin.setVisible(false);
        errPassLogin.setVisible(false);
        errUserSignup.setVisible(false);
        errPassSignup.setVisible(false);
        frame.setLocation(448,183);
        frame.setSize(449,367);
        frame.setVisible(false);
        frame.setLayout(new FlowLayout());
        frame.add(btnViewVideos);
        frame.add(btnAddVideos);
        frame.add(database);
        database.setModel(new DefaultTableModel(new Object [][] {}, new String[] {"Video Title","URL","Description"}));
        jsp = new JScrollPane(database);
        frame.add(jsp);
        jsp.setViewportView(database);
        jsp.setVisible(true);        
        datamodel1 = (DefaultTableModel) database.getModel();
        database.setVisible(false);
        frame.add(lblVideoTitle).setVisible(false);
        frame.add(txtVideoTitle).setVisible(false);
        frame.add(lblURL).setVisible(false);
        frame.add(txtURL).setVisible(false);
        frame.add(lblDesc).setVisible(false);
        frame.add(txtDesc).setVisible(false);
        frame.add(btnSubmitVideos).setVisible(false);
        frame.add(lblError).setVisible(false);
        lblError.setForeground(Color.red);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }
    Controller controller = new Controller();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPassSignup1 = new javax.swing.JLabel();
        pwdUserSignup1 = new javax.swing.JPasswordField();
        lblUserSignup = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtUserSignup = new javax.swing.JTextField();
        lblUserLogin = new javax.swing.JLabel();
        lblPassLogin = new javax.swing.JLabel();
        txtUserLogin = new javax.swing.JTextField();
        lblPassSignup2 = new javax.swing.JLabel();
        pwdUserSignup2 = new javax.swing.JPasswordField();
        lblTitle = new javax.swing.JLabel();
        btnSignup = new javax.swing.JButton();
        lblCreateAccount = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        pwdUserLogin = new javax.swing.JPasswordField();
        errUserLogin = new javax.swing.JLabel();
        errPassLogin = new javax.swing.JLabel();
        errUserSignup = new javax.swing.JLabel();
        errPassSignup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPassSignup1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPassSignup1.setText("Password:");

        lblUserSignup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserSignup.setText("Username:");

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblLogin.setText("Login");

        lblUserLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserLogin.setText("Username:");

        lblPassLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPassLogin.setText("Password:");

        lblPassSignup2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPassSignup2.setText("Confirm Password:");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Online Videos URL Database");

        btnSignup.setText("Signup");

        lblCreateAccount.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCreateAccount.setText("Create an account");

        btnLogin.setText("Login");

        errUserLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        errUserLogin.setForeground(new java.awt.Color(255, 0, 0));
        errUserLogin.setText("Username Does not exist!");

        errPassLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        errPassLogin.setForeground(new java.awt.Color(255, 0, 0));
        errPassLogin.setText("Wrong Password!");

        errUserSignup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        errUserSignup.setForeground(new java.awt.Color(255, 0, 0));
        errUserSignup.setText("Username already exist!");

        errPassSignup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        errPassSignup.setForeground(new java.awt.Color(255, 0, 0));
        errPassSignup.setText("Password Does not match!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblUserLogin)
                        .addGap(10, 10, 10)
                        .addComponent(txtUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errUserLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblPassLogin)
                        .addGap(10, 10, 10)
                        .addComponent(pwdUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errPassLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblCreateAccount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblUserSignup)
                        .addGap(10, 10, 10)
                        .addComponent(txtUserSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errUserSignup))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblPassSignup1)
                        .addGap(10, 10, 10)
                        .addComponent(pwdUserSignup1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblPassSignup2)
                        .addGap(10, 10, 10)
                        .addComponent(pwdUserSignup2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errPassSignup))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblTitle)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitle)
                .addGap(11, 11, 11)
                .addComponent(lblLogin)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblUserLogin))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errUserLogin)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblPassLogin))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pwdUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errPassLogin)))
                .addGap(6, 6, 6)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblCreateAccount)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblUserSignup))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUserSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errUserSignup)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblPassSignup1))
                    .addComponent(pwdUserSignup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblPassSignup2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pwdUserSignup2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errPassSignup)))
                .addGap(6, 6, 6)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void btnSignupActionListener(ActionListener signup) {
        btnSignup.addActionListener(signup);
    }
    void btnLoginActionListener(ActionListener login) {
        btnLogin.addActionListener(login);
    }
    protected String gettxtUserLogin() {
        return txtUserLogin.getText();
    }
    protected char[] getpwdUserLogin() {
        return pwdUserLogin.getPassword();
    }
    protected char[] getpwdUserSignup1() {
        return pwdUserSignup1.getPassword();
    }
    protected char[] getpwdUserSignup2() {
        return pwdUserSignup2.getPassword();
    }
    void btnViewVideosActionListener(ActionListener viewvideos) {
        btnViewVideos.addActionListener(viewvideos);
    } 
    void btnAddVideosActionListener(ActionListener addvideos) {
        btnAddVideos.addActionListener(addvideos);
    }
    void btnSubmitVideosActionListener(ActionListener addvideos) {
        btnSubmitVideos.addActionListener(addvideos);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnLogin;
    protected javax.swing.JButton btnSignup;
    public javax.swing.JLabel errPassLogin;
    public javax.swing.JLabel errPassSignup;
    public javax.swing.JLabel errUserLogin;
    public javax.swing.JLabel errUserSignup;
    public javax.swing.JLabel lblCreateAccount;
    public javax.swing.JLabel lblLogin;
    public javax.swing.JLabel lblPassLogin;
    public javax.swing.JLabel lblPassSignup1;
    public javax.swing.JLabel lblPassSignup2;
    public javax.swing.JLabel lblTitle;
    public javax.swing.JLabel lblUserLogin;
    public javax.swing.JLabel lblUserSignup;
    protected javax.swing.JPasswordField pwdUserLogin;
    protected javax.swing.JPasswordField pwdUserSignup1;
    protected javax.swing.JPasswordField pwdUserSignup2;
    protected javax.swing.JTextField txtUserLogin;
    protected javax.swing.JTextField txtUserSignup;
    // End of variables declaration//GEN-END:variables
}
